#!/bin/bash

set -e

mkdir build
cd build

echo ">> Config CMake ($COMPILER, $BUILDTYPE)"

cmake ../ -DWITH_WARNINGS=1 -DSCRIPTS=dynamic -DWITH_DYNAMIC_LINKING=1 -DTOOLS=1 -DNOJEM=0 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10

cd ..
