-- Fix Startup Errors
-- DELETE FROM `creature_addon` WHERE `guid` IN (103589,104200); -- already deleted on TC.. so no id to see.. By ArkDB
-- DELETE FROM `waypoint_scripts` WHERE `id` IN (460,461);
